// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz636mvUhUHBe_MF-ENFlgOhihxg98mpI',
    appId: '1:985537172035:web:8fa404e48b6cf99e643af6',
    messagingSenderId: '985537172035',
    projectId: 'onetoone-adb73',
    authDomain: 'onetoone-adb73.firebaseapp.com',
    storageBucket: 'onetoone-adb73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtjQ1n6i1hQ9BO-Jj1A5ZTadV80NrJYW8',
    appId: '1:985537172035:android:1718c14c5da22216643af6',
    messagingSenderId: '985537172035',
    projectId: 'onetoone-adb73',
    storageBucket: 'onetoone-adb73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQDFgoQFZS_wMdVVVITODBC3Yk-6Xt3tg',
    appId: '1:985537172035:ios:4d4ef7c26092eda1643af6',
    messagingSenderId: '985537172035',
    projectId: 'onetoone-adb73',
    storageBucket: 'onetoone-adb73.appspot.com',
    androidClientId: '985537172035-hmntf1aje5lprf4huhdc9tqvubjqtp6m.apps.googleusercontent.com',
    iosClientId: '985537172035-v4essmbnipgvbjnno73a1r4vt8kdchv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneToOne',
  );
}
